apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    link.argocd.argoproj.io/external-link: https://app.komodor.com/main/deep-dive/wspddemo.wspd-demo-default.guestbook
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/guestbook: https://github.com/damuret/guestbook
    app.komodor.com/guestbook.ref:  eb0420f75e3b9e3ba7c64bffabe672b454fbd274
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        owner: dan
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "15Mi"
        name: guestbook-ui
        ports:
        - containerPort: 80
